version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - node_modules_volume:/app/node_modules
    ports:
     - '8000:8000'
    command: npm run dev

volumes:
  node_modules_volume:
